### ISSUE TITLE
org.scalameta.UnreachableError: this code path should've been unreachable

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/stryker4s#939] opened 2021-08-13 07:55 UTC
### Summary

In some project I see stryker fail with the following error:
```
[info] Setting up mutated environment...
[error] org.scalameta.UnreachableError: this code path should've been unreachable
[error] 	at org.scalameta.UnreachableError$.raise(package.scala:40)
[error] 	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.isAmbiguousWithPatVarTerm$1(TreeSyntax.scala:242)
[error] 	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.isAmbiguousInParent$1(TreeSyntax.scala:278)
[error] 	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$guessIsBackquoted$7(TreeSyntax.scala:285)
[error] 	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$guessIsBackquoted$7$adapted(TreeSyntax.scala:285)
[error] 	at scala.Option.exists(Option.scala:240)
...
```

If I turn on Debug, I can see that the most recent message is always a `"[debug] Writing /x/y/z.scala file to /x/target-6103655613823871362/y/z.scala"`, whereafter if I add a `"!y/x.scala"` to `mutate:[...]`, it eventually hits another (very trivial, like just a case class) source file with the same type of error. This project is using [sangria-graphql](https://github.com/sangria-graphql/sangria) but I'm not sure yet if that is a surefire way of reproducing it.

**Comment by hugo-vrijswijk** [comment] 2021-08-13 10:42
This is a parsing error of Scalameta where it thinks it cannot construct valid code out of a tree.

Does the file have a pattern match that looks something like `case x @ Y => ...`? Specifically, the `@ Y` where `Y` is upper-case and without brackets (like matching on a case object)? If so, it is fixed by the next Scalameta release (https://github.com/scalameta/scalameta/pull/2448). 

If not, there might be a different issue. Do you think you could share a small code example that reproduces the issue?

**Comment by hugo-vrijswijk** [comment] 2022-03-16 09:14
Closing due to inactivity. If you are still running into this, don't hesitate to re-open the issue

**Closed by hugo-vrijswijk** 2022-03-16 09:14 UTC
